// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import { group } from "k6";

export let options = { maxRedirects: 4, timeout: '3s' };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    hostname: "docker.stack:9511"
  }
});

export function setup() {
  postman[Request]({
    name: "Welcome",
    id: "4d95878c-6f40-4108-9a4a-1affd4a0b519",
    method: "GET",
    address: "http://{{hostname}}/?profile_start=k6-load"
  });
}

export default function() {

  group("Coroutines/Web", function() {
    postman[Request]({
      name: "Welcome",
      id: "1c6599b8-b00a-4724-8829-7bf118ceb980",
      method: "GET",
      address: "http://{{hostname}}/"
    });

    // postman[Request]({
    //   name: "Sleep",
    //   id: "d6f16d03-e71c-4139-9977-657b8eff5b84",
    //   method: "GET",
    //   address: "http://{{hostname}}/sleep"
    // });

    postman[Request]({
      name: "Doctrine",
      id: "7eef06ec-9781-4bcf-b682-5540f67ba56b",
      method: "GET",
      address: "http://{{hostname}}/doctrine"
    });

    postman[Request]({
      name: "Doctrine Advanced",
      id: "01c08f46-ce2d-48bc-beac-32a01623d8f2",
      method: "GET",
      address: "http://{{hostname}}/doctrine-advanced"
    });
  });
}

export function teardown(data) {
  postman[Request]({
    name: "Welcome",
    id: "4d95878c-6f40-4108-9a4a-1affd4a0b519",
    method: "GET",
    address: "http://{{hostname}}/?profile_stop=k6-load"
  });
}
