#!/usr/bin/env php
<?php

use K911\Swoole\Tests\Fixtures\Symfony\TestAppKernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\ErrorHandler\Debug;

\set_time_limit(0);

require __DIR__.'/../../../../vendor/autoload.php';

if (!\class_exists(Application::class)) {
    throw new \RuntimeException('You need to add "symfony/framework-bundle" as a Composer dependency.');
}

$input = new ArgvInput();
$env = $input->getParameterOption(['--env', '-e'], $_SERVER['APP_ENV'] ?? 'test');
$overrideProdEnv = $input->getParameterOption(['--override-prod-env', '-o'], $_SERVER['OVERRIDE_PROD_ENV'] ?? null);
$debug = ($_SERVER['APP_DEBUG'] ?? ('prod' !== $env)) && !$input->hasParameterOption(['--no-debug', '']);

if ($debug) {
    \umask(0000);

    if (\class_exists(Debug::class)) {
        Debug::enable();
    }
}

$argv = $_SERVER['argv'];
$argv = array_filter($argv, fn (string $arg): bool => strpos($arg, '--override-prod-env') === false && strpos($arg, '-o ') === false);
$input = new ArgvInput($argv);

$kernel = new TestAppKernel($env, $debug, $overrideProdEnv);
$application = new Application($kernel);
$application->run($input);
