<?php

declare(strict_types=1);

namespace SwooleBundle\SwooleBundle\Tests\Unit\Server\Grpc\Attribute;

use PHPUnit\Framework\TestCase;
use SwooleBundle\SwooleBundle\Server\Grpc\Attribute\GrpcService;
use SwooleBundle\SwooleBundle\Server\Grpc\Context\ContextInterface;
use SwooleBundle\SwooleBundle\Server\Grpc\GrpcService as GrpcServiceInterface;
use SwooleBundle\SwooleBundle\Server\Grpc\Service\ServiceNameResolver;
use SwooleBundle\SwooleBundle\Tests\Unit\Server\Grpc\Service\Stub\StubMessage;

/**
 * Example services demonstrating attribute-based configuration.
 */
#[GrpcService]
class ExampleAutoNameService
{
    public function exampleMethod(ContextInterface $context, StubMessage $request): StubMessage
    {
        return new StubMessage();
    }
}

#[GrpcService(name: 'CustomName')]
class ExampleCustomNameService
{
    public function exampleMethod(ContextInterface $context, StubMessage $request): StubMessage
    {
        return new StubMessage();
    }
}

#[GrpcService(package: 'myapp')]
class ExamplePackageService
{
    public function exampleMethod(ContextInterface $context, StubMessage $request): StubMessage
    {
        return new StubMessage();
    }
}

#[GrpcService(name: 'Users', package: 'myapp.v1')]
class ExampleFullConfigService
{
    public function exampleMethod(ContextInterface $context, StubMessage $request): StubMessage
    {
        return new StubMessage();
    }
}

class ExampleInterfaceService implements GrpcServiceInterface
{
    public const NAME = '/legacy.InterfaceService';

    public function exampleMethod(ContextInterface $context, StubMessage $request): StubMessage
    {
        return new StubMessage();
    }
}

#[GrpcService(package: '')]
class ExampleEmptyPackageService
{
    public function exampleMethod(ContextInterface $context, StubMessage $request): StubMessage
    {
        return new StubMessage();
    }
}

/**
 * Tests for ServiceNameResolver with attribute-based services.
 */
final class ServiceNameResolverTest extends TestCase
{
    public function testAutoGeneratedName(): void
    {
        $resolver = new ServiceNameResolver();
        $service = new ExampleAutoNameService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/ExampleAutoNameService', $name);
    }

    public function testCustomName(): void
    {
        $resolver = new ServiceNameResolver();
        $service = new ExampleCustomNameService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/CustomName', $name);
    }

    public function testPackageOnly(): void
    {
        $resolver = new ServiceNameResolver();
        $service = new ExamplePackageService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/myapp.ExamplePackageService', $name);
    }

    public function testFullConfiguration(): void
    {
        $resolver = new ServiceNameResolver();
        $service = new ExampleFullConfigService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/myapp.v1.Users', $name);
    }

    public function testGlobalPackage(): void
    {
        $resolver = new ServiceNameResolver('globalapp');
        $service = new ExampleAutoNameService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/globalapp.ExampleAutoNameService', $name);
    }

    public function testAttributePackageOverridesGlobal(): void
    {
        $resolver = new ServiceNameResolver('globalapp');
        $service = new ExamplePackageService();

        $name = $resolver->resolve($service);

        // Attribute package 'myapp' overrides global 'globalapp'
        $this->assertEquals('/myapp.ExamplePackageService', $name);
    }

    public function testInterfaceBasedService(): void
    {
        $resolver = new ServiceNameResolver();
        $service = new ExampleInterfaceService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/legacy.InterfaceService', $name);
    }

    public function testInterfaceBasedServiceIgnoresGlobalPackage(): void
    {
        $resolver = new ServiceNameResolver('globalapp');
        $service = new ExampleInterfaceService();

        $name = $resolver->resolve($service);

        // Interface NAME takes precedence
        $this->assertEquals('/legacy.InterfaceService', $name);
    }

    public function testEmptyPackageAttribute(): void
    {
        $resolver = new ServiceNameResolver('defaultpkg');
        $service = new ExampleEmptyPackageService();

        $name = $resolver->resolve($service);

        // Empty package attribute should result in no package
        $this->assertEquals('/ExampleEmptyPackageService', $name);
    }

    public function testNullGlobalPackage(): void
    {
        $resolver = new ServiceNameResolver(null);
        $service = new ExampleAutoNameService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/ExampleAutoNameService', $name);
    }

    public function testEmptyGlobalPackage(): void
    {
        $resolver = new ServiceNameResolver('');
        $service = new ExampleAutoNameService();

        $name = $resolver->resolve($service);

        $this->assertEquals('/ExampleAutoNameService', $name);
    }
}
